<?php

/**
 * Get the Two Tap Purchase by the Two Tap purchase_id
 *
 * @param  [type] $purchase_id [description]
 *
 * @return [type]              [description]
 */
function get_twotap_purchase($purchase_id = null){
    if( is_null($purchase_id) ){
        return false;
    }

    $args = array(
        'post_type' => TT_POST_TYPE_PURCHASE,
        'post_status' => twotap_db_purchase_statuses(),
        'posts_per_page' => '-1',
        'order' => 'DESC',
        'orderby' => 'post_modified',
        'meta_query' => array(
            array(
                'key' => TT_META_TWOTAP_PURCHASE_ID,
                'value' => $purchase_id,
                'compare' => '=',
                )
            )
        );
    $query = new WP_Query($args);

    if($query->have_posts()){
        $present = $query->get_posts();
        $db_purchase = array_shift($present);
        return $db_purchase;
    } else {
        return false;
    }

}

/**
 * Convert the WooCommerce country to the Two Tap format
 *
 * @param  [type] $country [description]
 *
 * @return [type]          [description]
 */
function convert_country_code( $country ) {
    $tt_country_codes = array(
        'AU' => 'Australia',
        'CA' => 'Canada',
        'IE' => 'Ireland',
        'GB' => 'United Kingdom',
        'JP' => 'Japan',
        'RO' => 'Romania',
        'US' => 'United States of America',

        'AF' => 'Afghanistan',
        'AX' => '&#197;land Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BQ' => 'Bonaire, Saint Estatius and Saba',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Islands',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, Democratic Republic of the',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Côte d\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Curaçao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island and McDonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran',
        'IQ' => 'Iraq',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'Korea, Democratic People\'s Republic of',
        'KR' => 'Korea, Republic of (South)',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Laos',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao S.A.R., China',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RU' => 'Russia',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barth&eacute;lemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin (French part)',
        'SX' => 'Sint Maarten / Saint Matin (Dutch part)',
        'PM' => 'Saint Pierre and Miquelon',
        'VC' => 'Saint Vincent and the Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia/Sandwich Islands',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard and Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syria',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'UM' => 'United States Minor Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Island, U.S.',
        'WF' => 'Wallis and Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    );
    return isset( $tt_country_codes[$country] ) ? $tt_country_codes[$country] : $country;
}

/**
 * Convert the WooCommerce state to the Two Tap format
 *
 * @param  [type] $state   [description]
 * @param  [type] $country [description]
 *
 * @return [type]          [description]
 */
function convert_state_code( $state, $country ) {
    $tt_state_codes = array(
        'United States of America' => array(
            'AL' => 'Alabama',
            'AK' => 'Alaska',
            'AZ' => 'Arizona',
            'AR' => 'Arkansas',
            'AA' => 'Armed Forces Americas',
            'AE' => 'Armed Forces Europe',
            'AP' => 'Armed Forces Pacific',
            'CA' => 'California',
            'CO' => 'Colorado',
            'CT' => 'Connecticut',
            'DE' => 'Delaware',
            'DC' => 'District Of Columbia',
            'FL' => 'Florida',
            'GA' => 'Georgia',
            'HI' => 'Hawaii',
            'ID' => 'Idaho',
            'IL' => 'Illinois',
            'IN' => 'Indiana',
            'IA' => 'Iowa',
            'KS' => 'Kansas',
            'KY' => 'Kentucky',
            'LA' => 'Louisiana',
            'ME' => 'Maine',
            'MD' => 'Maryland',
            'MA' => 'Massachusetts',
            'MI' => 'Michigan',
            'MN' => 'Minnesota',
            'MS' => 'Mississippi',
            'MO' => 'Missouri',
            'MT' => 'Montana',
            'NE' => 'Nebraska',
            'NV' => 'Nevada',
            'NH' => 'New Hampshire',
            'NJ' => 'New Jersey',
            'NM' => 'New Mexico',
            'NY' => 'New York',
            'NC' => 'North Carolina',
            'ND' => 'North Dakota',
            'OH' => 'Ohio',
            'OK' => 'Oklahoma',
            'OR' => 'Oregon',
            'PA' => 'Pennsylvania',
            'RI' => 'Rhode Island',
            'SC' => 'South Carolina',
            'SD' => 'South Dakota',
            'TN' => 'Tennessee',
            'TX' => 'Texas',
            'UT' => 'Utah',
            'VT' => 'Vermont',
            'VA' => 'Virginia',
            'WA' => 'Washington',
            'WV' => 'West Virginia',
            'WI' => 'Wisconsin',
            'WY' => 'Wyoming',
        ),
        'Canada' => array(
            'AB' => 'Alberta',
            'BC' => 'British Columbia',
            'MB' => 'Manitoba',
            'NB' => 'New Brunswick',
            'NL' => 'Newfoundland/Labrador',
            'NT' => 'Northwest Territories',
            'NS' => 'Nova Scotia',
            'NU' => 'Nunavut',
            'ON' => 'Ontario',
            'PE' => 'Prince Edward Island',
            'QC' => 'Quebec',
            'SK' => 'Saskatchewan',
            'YT' => 'Yukon',
        ),
        'Australia' => array(
            'ACT' => 'Australian Capital Territory',
            'NSW' => 'New South Wales',
            'NT'  => 'Northern Territory',
            'QLD' => 'Queensland',
            'SA'  => 'South Australia',
            'TAS' => 'Tasmania',
            'VIC' => 'Victoria',
            'WA'  => 'Western Australia',
        ),
        'Ireland' => array(
            'CE' => 'Clare',
            'CK' => 'Cork',
            'CN' => 'Cavan',
            'CW' => 'Carlow',
            'DL' => 'Donegal',
            'DN' => 'Dublin',
            'GY' => 'Galway',
            'KE' => 'Kildare',
            'KK' => 'Kilkenny',
            'KY' => 'Kerry',
            'LD' => 'Longford',
            'LH' => 'Louth',
            'LK' => 'Limerick',
            'LM' => 'Leitrim',
            'LS' => 'Laois',
            'MH' => 'Meath',
            'MN' => 'Monaghan',
            'MO' => 'Mayo',
            'OY' => 'Offaly',
            'RN' => 'Roscommon',
            'SO' => 'Sligo',
            'TY' => 'Tipperary',
            'WD' => 'Waterford',
            'WH' => 'Westmeath',
            'WW' => 'Wicklow',
            'WX' => 'Wexford',
        ),
        'Turkey' => array(
            'TR01' => 'Adana',
            'TR02' => 'Adıyaman',
            'TR03' => 'Afyon',
            'TR04' => 'Ağrı',
            'TR05' => 'Amasya',
            'TR06' => 'Ankara',
            'TR07' => 'Antalya',
            'TR08' => 'Artvin',
            'TR09' => 'Aydın',
            'TR10' => 'Balıkesir',
            'TR11' => 'Bilecik',
            'TR12' => 'Bingöl',
            'TR13' => 'Bitlis',
            'TR14' => 'Bolu',
            'TR15' => 'Burdur',
            'TR16' => 'Bursa',
            'TR17' => 'Çanakkale',
            'TR18' => 'Çankırı',
            'TR19' => 'Çorum',
            'TR20' => 'Denizli',
            'TR21' => 'Diyarbakır',
            'TR22' => 'Edirne',
            'TR23' => 'Elazığ',
            'TR24' => 'Erzincan',
            'TR25' => 'Erzurum',
            'TR26' => 'Eskişehir',
            'TR27' => 'Gaziantep',
            'TR28' => 'Giresun',
            'TR29' => 'Gümüşhane',
            'TR30' => 'Hakkari',
            'TR31' => 'Hatay',
            'TR32' => 'Isparta',
            'TR33' => 'Mersin',
            'TR34' => 'İstanbul',
            'TR35' => 'İzmir',
            'TR36' => 'Kars',
            'TR37' => 'Kastamonu',
            'TR38' => 'Kayseri',
            'TR39' => 'Kırklareli',
            'TR40' => 'Kırşehir',
            'TR41' => 'Kocaeli',
            'TR42' => 'Konya',
            'TR43' => 'Kütahya',
            'TR44' => 'Malatya',
            'TR45' => 'Manisa',
            'TR46' => 'Kahramanmaraş',
            'TR47' => 'Mardin',
            'TR48' => 'Muğla',
            'TR49' => 'Muş',
            'TR50' => 'Nevşehir',
            'TR51' => 'Niğde',
            'TR52' => 'Ordu',
            'TR53' => 'Rize',
            'TR54' => 'Sakarya',
            'TR55' => 'Samsun',
            'TR56' => 'Siirt',
            'TR57' => 'Sinop',
            'TR58' => 'Sivas',
            'TR59' => 'Tekirdağ',
            'TR60' => 'Tokat',
            'TR61' => 'Trabzon',
            'TR62' => 'Tunceli',
            'TR63' => 'Şanlıurfa',
            'TR64' => 'Uşak',
            'TR65' => 'Van',
            'TR66' => 'Yozgat',
            'TR67' => 'Zonguldak',
            'TR68' => 'Aksaray',
            'TR69' => 'Bayburt',
            'TR70' => 'Karaman',
            'TR71' => 'Kırıkkale',
            'TR72' => 'Batman',
            'TR73' => 'Şırnak',
            'TR74' => 'Bartın',
            'TR75' => 'Ardahan',
            'TR76' => 'Iğdır',
            'TR77' => 'Yalova',
            'TR78' => 'Karabük',
            'TR79' => 'Kilis',
            'TR80' => 'Osmaniye',
            'TR81' => 'Düzce',
        ),
    );
    if(isset( $tt_state_codes[$country] )){
        return isset( $tt_state_codes[$country][$state] ) ? $tt_state_codes[$country][$state] : $state;
    }
    return $state;
}